### ISSUE TITLE
Unable to build after latest update of `ring` crate

### ISSUE THREAD

**Issue by vityafx** [dmizuk/twitter-stream-rs#13]
I have found interesting thing: I can't compile my crate which uses `twitter-stream` anymore. [According to what contributors of `ring` crate say](https://github.com/briansmith/ring/issues/537) it is impossible to link to more than one `ring` crate at once but you do.

Please, do something to make your crate use one version of `ring` crate at a time.

**Comment by dmizuk** [comment]
I've just uploaded version 0.3.1 which should fix this issue.

**Comment by vityafx** [comment]
Yes, it works now!
