### ISSUE TITLE
Can't compile - the crate depends on a yanked chrono 0.3.1

### ISSUE THREAD

**Issue by vityafx** [dmizuk/twitter-stream-rs#14]
Please take a look at https://crates.io/crates/chrono, the version you depend was yanked, change it to 0.4 asap please.

**Comment by vityafx** [comment]
Don't know what happened, I see your crates depend on 0.4 now but my Cargo.toml fails to get this..

**Comment by vityafx** [comment]
Ah, well, I have found the problem. Your main crate `twitter-stream` depends on old `twitter-stream-message` (version 0.1) which uses yanked 0.3.1 chrono. Fix it asap please!

**Comment by dmizuk** [comment]
I'm going to publish the fixed version of `twitter-stream` once azyobuzin/tweetust#5 is released.

**Comment by vityafx** [comment]
When I tried to compile `twitter-stream` with 0.2 version of `twitter-stream-message` I got the same error on `tweetust` crate, so both crates are have to publish updated crates.

**Comment by dmizuk** [comment]
[`v0.5.2`](https://crates.io/crates/twitter-stream/0.5.2) is released with support for `chrono 0.4`.
