### ISSUE TITLE
Release the new version of crate with new serde version

### ISSUE THREAD

**Issue by vityafx** [dmizuk/twitter-stream-rs#9]
A lot of projects have already moved to updated serde and updated their crates. There is such situation that each crate is capable of working with serde 1.0 but your crate does not (0.2.0 still needs old serde). Could you release new version of the crate quicker please? At the very least release `0.3` with only serde changes and continue work on the crate for the 0.4 version.

**Comment by dmizuk** [comment]
Thanks for your advice!
I've just published v0.3.0 to crates.io.
